[package]
org= "ballerina"
name= "integrationTest"
version= "2.0.0"

[build-options]
observability-included=true

[[dependency]]
org = "ballerina"
name = "io"
version = "@stdlib.io.version@"

[[dependency]]
org = "ballerina"
name = "stringutils"
version = "@stdlib.stringutils.version@"

[[dependency]]
org = "ballerina"
name = "config"
version = "@stdlib.config.version@"

[[dependency]]
org = "ballerina"
name = "system"
version = "@stdlib.system.version@"

[[dependency]]
org = "ballerina"
name = "http"
version = "@stdlib.http.version@"

[[dependency]]
org = "ballerina"
name = "log"
version = "@stdlib.log.version@"

[[platform.java11.dependency]]
path = "../module-ballerina-openapi/build/libs/module-ballerina-openapi-@project.version@.jar"
groupId = "ballerina"
artifactId = "openapi"
version = "@project.version@"
